int _putchar(char c);
int _isupper(int x);
int _isdigit(int c);
int mul(int a, int b);
void ptint_numbers(void);
void print_most_numbers(void);
void more_numbers(void);
void print_line(void n);
void print_diogonal(void n);
void print_sqare(int size);
void print_number(int n);
